#!/bin/bash
# "guess" guesses the character encoding of a file and sets its tag accordingly.
# Basically, we just check whether the file contains bytes that represent lowercase
# letters in EBCDIC, since these bytes are unlikely to be found in ASCII. Of course,
# this won't work IF YOU REALLY LIKE SHOUTING.
for var in "$@" ; do
	echo "Removing tag..."
	chtag -r $var
	if [[ `cat -B $var | tr -Cd '\000' | wc -c` -ne 0 ]] ; then
		echo "Tagging as binary..."
		chtag -b $var
	elif [[ `cat -B $var | tr -d [:lower:] | wc -c` -lt `cat $var | wc -c` ]] ; then
		echo "Tagging as EBCDIC..."
		chtag -tc 1047 $var
	else
		echo "Tagging as ASCII..."
		chtag -tc ISO8859-1 $var
	fi
done
